### ISSUE TITLE
"Link account" is absent

### ISSUE THREAD

**Issue by Arderos** [oznu/homebridge-gsh#1]
On version 0.0.2 of the plugin the "Links account" is absent in the plugin configuration window - only "Name" and "Token" fields are present

**Comment by oznu** [comment]
Hi @Arderos ,

Thanks for your interest in this plugin.

![4CFD40FF-02E0-4EEF-9964-826BD1217C1F](https://user-images.githubusercontent.com/3979615/61965813-7fb65100-b014-11e9-8543-48a32dce6a78.jpeg)

This project is still a work in progress. The UI updates have not yet been published, nor has the corresponding Google Assistant action (currently under review).

**Comment by Arderos** [comment]
No problem. Best of luck to you!

**Comment by oznu** [comment]
4.6.0 has been published and the Google Action is now live.
