### ISSUE TITLE
Temp/Humidity sensor

### ISSUE THREAD

**Issue by mgalb91** [oznu/homebridge-gsh#101]
Hi folks, I have already read, that there is support for temperature and humidity sensor. I can see temperature and humidity as accessory in GSH app, but there is no value. Is there still some problem with implementation this feature? Could someone help me? Thank you in advance

**Environment:**

* **Node.js Version**: v14.15.4
* **NPM Version**: 6.14.10
* **Homebridge Version**: 1.17
* **Homebridge GSH Plugin Version**: 2.0.1
* **Homebridge Config UI X Plugin Version**: 4.38.0
* **Operating System**: raspbian 10

**Comment by oznu** [comment]
Temperature sensors do not support visual / touch controls in the Google Home app.

See this page for a full list of device types that support visual control:

https://developers.google.com/assistant/smarthome/develop/touch-controls

You should be able to ask google verbally for the status of the sensor.

**Comment by mgalb91** [comment]
Thank you for your reply, and could you tell me for what reason I can use this sensor in smart home app? I can see that this plugin for HB support this kind of sensors. Thank you.

**Comment by oznu** [comment]
In the app it's not much use. This is a limitation of the Google Home app, not Homebridge or this plugin. 

The Google home app functionality focused mainly on voice control, it is not even close to being as featured as the Apple Home app.
