### ISSUE TITLE
Can’t get Google login 

### ISSUE THREAD

**Issue by treforparr** [oznu/homebridge-gsh#102]
You won’t get Google login on the authorisation page on hoobs same issue was about eight months ago  where it was and configure proper

**Comment by oznu** [comment]
Please contact HOOBS for support when using HOOBS.

**Comment by oznu** [comment]
Confirmed that both GitHub and Google authentication methods for the GSH plugin are working as expected via Homebridge UI.

**Comment by oznu** [comment]
See this article for solution:

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge
