### ISSUE TITLE
Google home is unable to retrive homebridge-gsh

### ISSUE THREAD

**Issue by Fremske** [oznu/homebridge-gsh#105]
After the latest update of Homebridge to 1.3.3 and GSH to 2.1.0 my Google home can not establish a connection with my Homebridge GSH plugin.

When trying to connect via https://homebridge-gsh.iot.oz.nu/link-account the spinner keeps turning and the plugin is not being detected by Google.

![image](https://user-images.githubusercontent.com/35497980/110951340-dd5bf600-833c-11eb-8f56-c69b0b27afd0.png)

**Comment by tedarion** [comment]
Have the same problems..... :(

**Comment by vespino** [comment]
Same here, I rolled back the plugin.

**Comment by Einstein2150** [comment]
Same here. Working connection doesn't work anymore 🤔
