### ISSUE TITLE
Unable to update GSH plugin in hoobs

### ISSUE THREAD

**Issue by fizulnizam** [oznu/homebridge-gsh#108]
As the title says, I am unable to update the gsh plugin in hoobs, it says 
`ERR!
24/03/2021, 14:57:42  code EEXIST
npm ERR! path /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/qrcode-terminal
24/03/2021, 14:57:42 npm
24/03/2021, 14:57:42 
24/03/2021, 14:57:42 ERR! Refusing to delete /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/qrcode-terminal: is outside /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/qrcode-terminal and not a link
npm ERR! File exists: /home/hoobs/.hoobs/node_modules/homebridge-gsh/node_modules/.bin/qrcode-terminal
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.`

I am running version 2.0.1 on hoobs 3.3.5
Hope to have a solution soon.

**Comment by oznu** [comment]
This plugin requires Homebridge:

https://github.com/oznu/homebridge-gsh#configuration

See https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge for details on how to move to a supported configuration. Hit me up on the Homebridge discord if you have any questions about this process.

**Comment by fizulnizam** [comment]
Isn’t HOOBS essentially homebridge?
