### ISSUE TITLE
Unable to Connect to GSH Servers

### ISSUE THREAD

**Issue by TransRapid** [oznu/homebridge-gsh#109]
My Pi has been running fine for a long time. Suddenly GSH fails to connect. I thought maybe it got signed out somehow. The reauthenticated. Issue is that it Links, then says it fails to connect to servers. Nothing unusual in the logs even with debugging. Also reset, reinstalled, rolled back. Nothing works.

I would also like to know about hosting my own mirror of the server.

**Comment by TransRapid** [comment]
Solved! (Work Around)

I just noticed I didn’t do a full restart after the rollback and reconfigure. I did it after each on their own, but not after doing both in the same debug process.

Version 2.0.1 works, current release of 2.1.0 does not.

**Comment by jeroenkl** [comment]
> Solved! (Work Around)
> 
> I just noticed I didn’t do a full restart after the rollback and reconfigure. I did it after each on their own, but not after doing both in the same debug process.
> 
> Version 2.0.1 works, current release of 2.1.0 does not.

same issue here

**Comment by kjlisby** [comment]
I saw the same thing. With 2.1.0 no connection could be established to the server and no link button would appear.
Rolling back to 2.0.1 solved it.

**Comment by Scrat95220** [comment]
> Solved! (Work Around)
> 
> I just noticed I didn’t do a full restart after the rollback and reconfigure. I did it after each on their own, but not after doing both in the same debug process.
> 
> Version 2.0.1 works, current release of 2.1.0 does not.

Hello,
Same issue for me

**Comment by BenGost** [comment]
> Résolu! (Solution de contournement)
> 
> Je viens de remarquer que je n'ai pas fait un redémarrage complet après la restauration et la reconfiguration. Je l'ai fait après chacun d'eux-mêmes, mais pas après avoir fait les deux dans le même processus de débogage.
> 
> La version 2.0.1 fonctionne, la version actuelle de 2.1.0 ne fonctionne pas.

Merci !

**Comment by jeroenkl** [comment]
Hmm, no update seen yet

**Comment by kjlisby** [comment]
Will none of the contributers to this project solve this issue? If nothing else, then please roll back the commit that introduced it.
Please note that even though some of the comments above says “solved”, it is actually not the case. We have all just rolled back to an older version in order to cope with it.

**Comment by TransRapid** [comment]
I am about to try updating again to see if perhaps something changed. I now noticed that in my logs I am getting a request to authenticate once more. Not sure what that is about.

**Comment by astrapowerrr** [comment]
Same here. Not working until rolled  back to 2.01. Cost me my evening to figure it out.

**Comment by leonhelmle** [comment]
Same here. Please fix :D

**Comment by kjlisby** [comment]
Hi @TransRapid,
If you can, it would be great to get this fixed.

**Comment by sankalpdomore** [comment]
@roshanraj got this library for HomeBridge but unable to connect to Google Home servers.

**Comment by TransRapid** [comment]
> @roshanraj got this library for HomeBridge but unable to connect to Google Home servers.

What version? Try rolling back to the mentioned 2.0.1. If that does not work try going back a little further. Where are you getting this error? Is it when trying to use it through a Google device such as a speaker, or upon initial setup?

**Comment by saggyhaggis** [comment]
@TransRapid 
Thanks, rolling back t 2.0.1 allowed me to link my google account.

**Comment by oznu** [comment]
I'm aware this service has had a few issues lately. I've finally gotten time to migrate the server component to new infrastructure that should handle the load more seamlessly.
