### ISSUE TITLE
thermostat degree displayed in Fahrenheit instead of celsius

### ISSUE THREAD

**Issue by romain1313** [oznu/homebridge-gsh#112]
homebridge v1.1.7
homebridge-daikin-local v2021.15.1
homebridge-gsh v2.0.1

Thermostat is displayed/convert in Fahrenheit instead of Celsius. 
is it possible to set Celcius by default ?

thanks in advance.

**Comment by oznu** [comment]
In the iOS Home app, go to the thermostat settings, make sure "Temperate Display Units" is set to "Celsius".
