### ISSUE TITLE
Settings does not display option to link

### ISSUE THREAD

**Issue by Ghitafjorback** [oznu/homebridge-gsh#114]
**Describe Your Problem:**

After installation of the plugin, I do not get the option to link account. I have enabled insecure mode.

**Logs:**

```
Show the Homebridge logs here.
Remove any sensative information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here. 
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/59295827/116806375-e3947480-ab2c-11eb-9a36-75e98abe0b11.jpeg)

**Environment:**

* **Node.js Version**: 14.16.1
* **NPM Version**: 6.14.12
* **Homebridge Version**: 1.3.4
* **Homebridge GSH Plugin Version**:2.1.0
* **Homebridge Config UI X Plugin Version**:4.41.1
- [ ] * **Operating System**: Raspbian

**Comment by Mks322** [comment]
I hva the same issue, found a solution?

**Comment by Ghitafjorback** [comment]
I used an earlier version, and then it works. 😣 I have not updated since, as I am afraid it won't work.

**Comment by Mks322** [comment]
ok! ill try that!
