### ISSUE TITLE
Support for air purifier device type

### ISSUE THREAD

**Issue by lensherm** [oznu/homebridge-gsh#117]
First let me apologize for not putting in too much in terms of details. I hurt my thumb so typing is not that easy for the next few days. 

Anyhow, pretty much like the header says, it would be nice to be able to control air purifiers' fan level from Homebridge using Google Home. Accessing the air quality and filter life data on the air purifiers are definitely great bonuses.

**Comment by ciak2009** [comment]
Any news on this?
