### ISSUE TITLE
Something Went Wrong

### ISSUE THREAD

**Issue by meluvalli** [oznu/homebridge-gsh#122]
Redid my HomeKit.  Was working fine with Google Home before and can't get it working anymore.

I opened "Google Home" app and Unlinked "HomeBridge".
I then cleared the Token out of HomeBridge Config file.
Restarted HomeBridge. 
Used Config-UI and linked HomeBridge to my GMail account.
Restarted HomeBridge.
I opened "Google Home" app and Linked HomeBridge by adding device.

It logs in.  Says ""Homebridge is linked" and waits... Then says "Something went wrong.  Try again.".

I have closed Google Home App and tried again, same results.  Any ideas?

**Comment by meluvalli** [comment]
Ok.  Figured this out on my own.

I use to be able to run "Google-smarthome" platform in a "separate" instance, but for whatever reason, I can't do this anymore.  Not sure if this changed with versions over time or what...

Anyhow, I moved the "Google-smarthome" platform in with my devices and switches and all is working now.

**Comment by ssammy** [comment]
Hello,
Topic is still open, I cannot link gsh to google account on smarrtphone

**Comment by AndrewReifel** [comment]
> Hello, Topic is still open, I cannot link gsh to google account on smartphone

Did you happen to solve this issue? i get the "Something went wrong error".
