### ISSUE TITLE
Device <Name of Device> is not ready. [Question]

### ISSUE THREAD

**Issue by kweronline** [oznu/homebridge-gsh#13]
Hi there! 
Just stumbled over this nice homebridge addon and got it set up so far,

However when im turning on my Lamps (which I've integrated using Zigbee2MQTT), Google tells me the Lamp isn't ready but turns it on regardless. Any idea on whats the cause of it?

**Comment by oznu** [comment]
Logs?

Your Homebridge device needs to respond within 5 seconds otherwise Google will timeout. Generally 5 seconds is plenty of time, the average I am seeing across all users is about 0.7 seconds.

**Comment by kweronline** [comment]
https://pastebin.com/k1bJ9mMG

Here's everything that happens after turning the lamp on (or off). The first it turned on and off just fine but then on the 2nd time it told me the device isn't ready and then turned the lamp on as if it was nothing.

**Comment by oznu** [comment]
Do you have more than one Homebridge instance?

**Comment by kweronline** [comment]
No, only a single instance hosted in docker

**Comment by oznu** [comment]
Can you check you don't inadvertently have another instance of your docker container running? I'm see two instances connecting from your account, from the same IP address, but with different usernames in the config.json.

**Comment by kweronline** [comment]
Turns out that I had a test instance outside of docker running without me knowing, shut that one down and now it's all good. (Besides changing the colour temperature)

Thank youm
