### ISSUE TITLE
Pairing does not Bring up the link account dialog 

### ISSUE THREAD

**Issue by Tesla-P100FX** [oznu/homebridge-gsh#134]
Running Hoobs and current GSH plugin.    After installation  i select the pair button but it does  does not Bring up the link account dialog so i cant set it up. 
Homebridge version 1.3.4 
Node Version       14.18.1
GSH Version        2.2.0

Config

{
    "platform": "google-smarthome"
}

**Comment by Bl4ckw0lf2022** [comment]
same thing for me

**Comment by Tesla-P100FX** [comment]
> Running Hoobs and current GSH plugin.    After installation  i select the pair button but it does  does not Bring up the link account dialog so i cant set it up. 
> 
> Homebridge version 1.3.4 
> 
> Node Version       14.18.1
> 
> GSH Version        2.2.0
> 
> 
> 
> Config
> 
> 
> 
> {
> 
>     "platform": "google-smarthome"
> 
> }
> 
> 
> 
> 

I was able to make this work.   I reinstalled.   Then installed the Hoobs 4 desktop homebridge app.  From there I went to GSH and clicked on pair.   It opened a Edge browser window but edge was blocking a pop up from my homebridge.  I allowed the pop up to open and there was the google dialog to link my account.    Everything working now.
