### ISSUE TITLE
Can't link Homebridge to Google Home app (LG TV)

### ISSUE THREAD

**Issue by realrEDGUY** [oznu/homebridge-gsh#137]
**Describe Your Problem:**

I have an LG TV linked to my Homekit app (lg-75up75006lc) but whenever I try to link the Homebridge app to Google Home it just errors out. I currently have nothing else linked to my Homekit app but my Google Home is full of lightbulbs

**Logs:**

```
[12/14/2021, 7:41:44 PM] [Google Smart Home] Received SYNC intent
[12/14/2021, 7:41:44 PM] [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "2595208034943843253"
    }
  ],
  "requestId": "2595208034943843253"
}
[12/14/2021, 7:41:44 PM] [Google Smart Home] No supported devices found. See https://git.io/JfuHW
[12/14/2021, 7:46:41 PM] [Google Smart Home] Sending full post-sync state report
```

**Homebridge Config:**

```json
{
    "bridge": {
        "name": "Homebridge 1775",
        "username": "",
        "port": 51893,
        "pin": ""
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Google Smart Home",
            "token": "",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome",
            "_bridge": {
                "username": "",
                "port": 32417
            }
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v16.13.1
* **NPM Version**: 8.1.2
* **Homebridge Version**: 1.3.8
* **Homebridge GSH Plugin Version**: homebridge-gsh v2.2.0
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.41.4
* **Operating System**: Ubuntu 18.04

**Comment by oznu** [comment]
This project allows you to control your supported [Homebridge](https://github.com/nfarina/homebridge) accessories in Google Home. It does not bring Google Home accessories into HomeKit.

**Comment by realrEDGUY** [comment]
> This project allows you to control your supported [Homebridge](https://github.com/nfarina/homebridge) accessories in Google Home. It does not bring Google Home accessories into HomeKit.

The LG tv is Homekit compatible not Google Home, but maybe it is not supported by Homebridge.
