### ISSUE TITLE
Homebridge devices are shown as shields in Google home without detailed information

### ISSUE THREAD

**Issue by StephT-89** [oznu/homebridge-gsh#139]
When configuring a link between homebridge and Google Assistant/Google home alle devices from Homebridge are shown, but it seams like the device type is not really identified. 

For example the following device:

`02/01/2022, 13:29:31] [Google Smart Home] [
  {
    id: '-----------------------------------------------------------',
    type: 'action.devices.types.SENSOR',
    traits: [ 'action.devices.traits.TemperatureControl' ],
    name: { defaultNames: [Array], name: 'DoorSensor', nicknames: [] },
    willReportState: true,
    attributes: { queryOnlyTemperatureControl: true, temperatureUnitForUX: 'C' },
    deviceInfo: {
      manufacturer: 'Xiaomi',
      model: 'MCCGQ11LM',
      hwVersion: undefined,
      swVersion: undefined
    },

{
            "name": "Google Smart Home",
            "token": "token_deleted",
            "notice": "Keep your token a secret!",
            "twoFactorAuthPin": "pin-deleted",
            "debug": true,
            "platform": "google-smarthome",
            "_bridge": {
                "username": "user_deleted",
                "port": 49843
            }
        },`
![Screenshot_20220102-143552_Home](https://user-images.githubusercontent.com/74459623/147877643-cbce912b-ff5e-43ca-83e0-617d2395c0ff.jpg)

pi@homebridge:~ $ node -v
v16.13.1
pi@homebridge:~ $ npm -v
8.1.2
pi@homebridge:~ $ homebridge -V
1.3.9

homebridge-gsh v2.2.0
homebridge-config-ui-x v4.41.5

"Raspbian GNU/Linux 11 (bullseye)

**Comment by minscof** [comment]
I can't get door sensor with Google Home, did you configure something to get that ?

**Comment by oznu** [comment]
The Google Home app doesn't support "visual" control of many accessory types, including sensors. You can ask Google verbally for their status.
