### ISSUE TITLE
plugin does not map all devices

### ISSUE THREAD

**Issue by mentaluproar** [oznu/homebridge-gsh#14]
**Describe Your Problem:**
I have 2 rooms with cree bulbs controlled through a phillips hue hub.  They are made compatible with apple homekit via homebridge-hue.  Only one room is mapped to homebridge-gsh.  The other room is ignored.  It also doesnt understand how to turn a living room light on and off, which is controlled by an idevices smart plug.

**Logs:**
 hapNodeJSClient Starting Homebridge instance discovery +0ms
  hapNodeJSClient HAP Device discovered BSB002 [ '10.0.1.185', 'fe80::217:88ff:fea4:60b5' ] +125ms
  hapNodeJSClient HAP instance address: BSB002 -> Philips-hue.local -> 10.0.1.185:8080 +2ms
  hapNodeJSClient HAP Discover failed BSB002 http://10.0.1.185:8080 error code 470 +48ms
  hapNodeJSClient HAP Device discovered IDEV0001 [ '10.0.1.124' ] +112ms
  hapNodeJSClient HAP instance address: IDEV0001 -> Switch-00006623.local -> 10.0.1.124:80 +2ms
  hapNodeJSClient HAP Device discovered ecobee3 lite [ '10.0.1.72',
  '2605:a000:122a:a0e5:4661:32ff:fe97:401f',
  'fe80::4661:32ff:fe97:401f' ] +10ms
  hapNodeJSClient HAP instance address: ecobee3 lite -> little-bee.local -> 10.0.1.72:1200 +1ms
  hapNodeJSClient HAP Discover failed IDEV0001 http://10.0.1.124:80 error code 470 +25ms
  hapNodeJSClient HAP Device discovered Homebridge [ '10.0.1.2' ] +82ms
  hapNodeJSClient HAP instance address: Homebridge -> CC_22_3D_E3_CE_30.local -> 10.0.1.2:51826 +1ms
  hapNodeJSClient Homebridge instance discovered Homebridge-CAD8 with 12 accessories +27ms
  hapNodeJSClient HAP Device discovered front door [ '10.0.1.2' ] +243ms
  hapNodeJSClient HAP instance address: front door -> 2C_86_18_3A_6D_96.local -> 10.0.1.2:52100 +2ms
  hapNodeJSClient Homebridge instance discovered front door-E83A with 1 accessories +25ms
  hapNodeJSClient HAP Discover failed ecobee3 lite http://10.0.1.72:1200 error code 470 +3s
  hapNodeJSClient Ending Homebridge instance discovery +7s
[9/7/2019, 3:22:42 PM] [Google Smart Home] Finished instance discovery
[9/7/2019, 3:22:42 PM] [Google Smart Home] HAP Event listeners registered succesfully
[9/7/2019, 3:22:57 PM] [Google Smart Home] Sending Sync Request

**Homebridge Config:**
{
    "bridge": {
        "name": "Homebridge",
        "username": “REDACTED”,
        "port": 51826,
        "pin": “REDACTED”
    },
    "description": "Homebridge server",
    "ports": {
        "start": 52100,
        "end": 52150,
        "comment": "whatever"
    },
    "accessories": [],
    "platforms": [
        {
            "platform": "Camera-ffmpeg",
            "cameras": [
                {
                    "name": "front door",
                    "videoConfig": {
                        "vcodec": "h264",
                        "source": "-re -i rtsp://REDACTED@10.0.1.125/live",
                        "maxStreams": 2,
                        "maxWidth": 1080,
                        "maxHeight": 720,
                        "maxFPS": 15
                    }
                }
            ]
        },
        {
            "platform": "Frigidaire",
            "name": "Frigidaire AC Units",
            "username": “REDACTED”,
            "password": “REDACTED”
        },
        {
            "platform": "HarmonyHubWebSocket",
            "name": "Harmony Hub",
            "hubIP": "10.0.1.27",
            "TVPlatformMode": true,
            "mainActivity": "Watch Apple TV",
            "showTurnOffActivity": "stateless"
        },
        {
            "platform": "Hue",
            "users": {
                “REDACTED”
            },
            "lights": true,
            "nativeHomeKitlights": true
        },
        {
            "platform": "config",
            "name": "Config",
            "port": 4200,
            "sudo": true,
            "restart": "sudo systemctl restart homebridge.service",
            "log": {
                "method": "systemd",
                "service": "homebridge"
            }
        },
        {
            "name": "Google Smart Home",
            "token": “REDACTED”,
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome",
            "debug": true
        }
    ]
}
**Environment:**

* **Node.js Version**:  10.16.3
* **NPM Version**: 6.11.2
* **Homebridge Version**:  0.4.50
* **Homebridge GSM Plugin Version**: 1.0.3
* **Homebridge Config UI X Plugin Version**: 4.6.1
* **Operating System**: Debian

**Comment by oznu** [comment]
Can you show the logs with debug mode turned on? Especially of interest is the response to the "SYNC" request that should happen 30-45 seconds after you restart homebridge.

![image](https://user-images.githubusercontent.com/3979615/64483589-2a42a600-d248-11e9-8473-9ac78c46f467.png)

**Comment by mentaluproar** [comment]
Nothing comes up after sending sync request.

FWIW, I discovered passwordless sudo does not work on my setup for the homebridge user unless I su into it and run homebridge from there.  It seems to ignore my sudo config when run via systemd.  I'm not sure that that's a problem or intended behavior by systemd.  I'd like to take sud away from it once it gets set up anyway.
