### ISSUE TITLE
Door sensor missing

### ISSUE THREAD

**Issue by minscof** [oznu/homebridge-gsh#140]
**Describe Your Problem:**

I have door sensor in homebridge, but they are not synchronised with GSH and so they are missing in google home 

Is this feature still avalaible ? does it depend of google home version ?

**Environment:**

* **Node.js Version**: v16.13.1
* **NPM Version**: v8.1.2
* **Homebridge Version**: 1.3.9
* **Homebridge GSH Plugin Version**: 2.2.0
* **Homebridge Config UI X Plugin Version**:v4.41.5
* **Operating System**: Raspbian
<html>
<body>

</body>
</html>

**Comment by Micha-123** [comment]
here the same, much Door sensors in Domoticz, i can see the Doors/windows in Homebridge, but not in Google.  is google supporting Door / window sensors or only door locks  ?

**Comment by oznu** [comment]
What type of sensor is the "door sensor"? HomeKit does not define as "Door Sensor"

**Comment by minscof** [comment]
I use this [sensor](https://www.zigbee2mqtt.io/devices/MCCGQ11LM.html#xiaomi-mccgq11lm).  Maybe, it can be mapped to contact sensor, if homekit defines that ?

**Comment by StephT-89** [comment]
Hi,
I would also like to use that door sensor. Have you been able to get it into Google Home? I only see the temperature of that device in Google Home.

**Comment by Micaaz** [comment]
Hello, I'm facing the same issue, only the temperature is available but not the sensor value...
Is there something else to do ?
