### ISSUE TITLE
Fan accessories not showing up

### ISSUE THREAD

**Issue by huongminh** [oznu/homebridge-gsh#15]
**Describe The Bug:**
All fan accessories from the plugin homebridge-broadlink-rm and homebridge-mi-fan do not show up in the Google Home App (I use iOS). They show up as unsupported devices in the Homebridge Config UI X accessories tab. I have a fake fan from the homebridge-marantz-volume plugin which however shows up with an on/off button.
**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsm / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge GSM Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by oznu** [comment]
FanV2 is now supported which will probably make these fan types show up. Only On/Off is currently supported as there are some issues with fan modes in the Google Smart Home ecosystem at the moment.

Ref:

```
https://github.com/actions-on-google/smart-home-nodejs/issues/238
```
