### ISSUE TITLE
Is it possible to show google home accesories to homekit?

### ISSUE THREAD

**Issue by Mitsosxat** [oznu/homebridge-gsh#150]
Hello, i have an ewpe controlled airconditoner (toyotomi) linked to my google home. i have homebridge.  is it possible to see the air conditoner as an accessory to homekit? i mean Control my supported google home accessories from homekit

**Comment by dnldcs** [comment]
I believe that accessory will work with the "Tuya" plug-in, so you would be link it directly.

**Comment by Mitsosxat** [comment]
I have a Toyotomi air conditioner that works with ewpe app inserted to google home. And I want to insert it to HomeKit because there is no plug-in in homebridge. I have tried many but nothing worked. I don’t think the tuya plug in will do the work except there is something I don’t get. Can you please explain further?

**Comment by dnldcs** [comment]
Tuya is a very very large company. They also sell lots of products to other companies, who sell them under their own name. Smart Life, Geeni Smarthome, and Merkury all are brands that are really Tuya. Also many companies use same protocol as Tuya.

I don't have an answer to your question on sending google home switches to Homekit.

**Comment by oznu** [comment]
Not with this project.
