### ISSUE TITLE
What context makes this tool meaningful?

### ISSUE THREAD

**Issue by merchako** [oznu/homebridge-gsh#151]
**Describe Your Problem:**

The intro of `ReadMe.md` leaves me with more questions than answers. 

- Why would I want to control my Homebridge accessories from Google Assistant? If I were to use Homebridge, it would be to connect all of my non-HomeKit devices to  HomeKit—and all of those devices are compatible with Google Home app. So why wouldn't I add them directly to Google Home?

- Can I control HomeKit from Google Assistant? Like, would this make it so I only need one smart home control center—HomeKit—and but I can still use Google Assistant devices to issue HomeKit commands?

I'm sure I'm missing something, and you have great answers to these questions. Perhaps it would help to (hint at) the answers in `ReadMe.md`. What's the story behind why _homebridge-gsh_ exists?

**Logs:** Not applicable.

**Homebridge Config:** Not applicable.

**Screenshots:** Not applicable.

**Environment:**

* **Node.js Version**: 17.4.0
* **NPM Version**: 8.3.1
* **Homebridge Version**: Not applicable—still deciding whether to adopt or not
* **Homebridge GSH Plugin Version**: Not applicable—still deciding whether to adopt or not
* **Homebridge Config UI X Plugin Version**: Not applicable—still deciding whether to adopt or not
* **Operating System**: macOS

**Comment by keuninkske** [comment]
i have only android, no homekit nothing
i have installed the GSH plugin

for me it is usefull

**Comment by oznu** [comment]
The project allows you to control your supported [Homebridge](https://github.com/nfarina/homebridge) accessories from Google Home. Helpful if you have household members that aren't iPhone users, or want to use much cheaper Google Nest Mini's vs HomePods.
