### ISSUE TITLE
Any chance for camera support as well?

### ISSUE THREAD

**Issue by Casuallynoted** [oznu/homebridge-gsh#16]
Specifically hoping to share homebridge cameras with GSH as well. And not sure if contact/motion sensors are supported with the latest versions of Google Home either.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Horndrup** [comment]
I would like that to.

**Comment by oznu** [comment]
The camera type is limited to asking the Google Assistant to beam your stream to a Chromcast compatible device, and requires a the video feed to be broadcast in a different format to what Apple requires. 

https://developers.google.com/assistant/smarthome/guides/camera.html

Maybe one day, but don't hold out for it. It should be possible but will require per-camera configuration.
