### ISSUE TITLE
Server is down ?

### ISSUE THREAD

**Issue by daserra23** [oznu/homebridge-gsh#169]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensitive information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here.
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge GSH Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by vskal** [comment]
Something must be down, I am getting this error message every second:
[6/5/2022, 11:38:33 AM] [Google Smart Home] Disconnected (2765) - Retry in 5000ms
[6/5/2022, 11:38:38 AM] [Google Smart Home] Reconnecting (2765)

**Comment by kornflex** [comment]
Same here

Seems to be done yesterday 11:00pm. Maybe before

**Comment by nl2rma** [comment]
Same here, disconnect/reconnect messages. After removing GSH configuration I tried to reconnect my Google account account and I receive a Bad Gateway message and no connection is made

**Comment by michael-loeffen** [comment]
> Same here, disconnect/reconnect messages. After removing GSH configuration I tried to reconnect my Google account account and I receive a "502 Bad Gateway" message and no connection is made

Also have the same messages

**Comment by daserra23** [comment]
Glad it's not just me. Hopefully it will come back online soon.

**Comment by Thiso6** [comment]
same here - also 502 Bad Gateway when trying to reconnect account

**Comment by itsxorf** [comment]
Same issue here. Have disabled the plugin for the moment.

**Comment by Torpidlittle** [comment]
Same here! 502 Bad Gateway error message…

**Comment by masav61** [comment]
Same here too!

**Comment by daserra23** [comment]
I believe the developer is in Australia so it is night-time there and we have just come out of a weekend also. Hopefully a minor issue, I love this plugin and very much appreciate the efforts put in.

**Comment by fellowgeek** [comment]
I am going to start sponsoring this project, I realize there is a cost to running the server, I think if we all gave $1 month will help ;) 
but yeah the server is down :'(

**Comment by SMADdie86** [comment]
Hello all, same issues here started 16 hours ago.
Lots of reconnecting after 5000ms (turns out to be 1100ms ;)) and then getting 502 and 503 errors, out off the blue.
Due that I recently started using docker I tought it might be an DNS or gateway issue, nope.
Placed the last good working image back, still same issue, my wife hateded me, but now understands its out off my hands :)

Hope that the issue can be resolved quickly have the impression it has something to do with the OAUTH updates of google it self?

**Comment by oznu** [comment]
I am currently abroad and don't have access to a computer at the moment to diagnose the problem. I'll try and get to this as soon as I can. I'd recommend disabling the plugin for now.

**Comment by oznu** [comment]
It should be back.

A new, much more powerful, server was commissioned a month or so ago to handle the increased number of users this service has.

It seems new server's default log rotate config wasn't good enough to stop the disk filling up which prevented new connections. 

Naturally it all stopped working the moment I got on a plane 😒

**Comment by Thiso6** [comment]
thanks a lot!! Verified to be working

**Comment by daserra23** [comment]
Also verified to be working, fantastic, donating now also.

**Comment by SMADdie86** [comment]
Oznu, yup works like a charm again.
Thnx for the fast solution and it is Murphys law isnt it.
Hope you can enjoy your holiday!

**Comment by michael-loeffen** [comment]
oznu,
thanks for the quick fix, works like a charm again. Also made a donation.
Enjoy your holiday!

**Comment by nl2rma** [comment]
Thank you Onzin.

**Comment by Torpidlittle** [comment]
Yes, it’s working now! Thanks a lot for this quick fix!

**Comment by masav61** [comment]
It’s working! Many, many thanks.

**Comment by yhur** [comment]
Thank you onzu!!!

**Comment by Thiso6** [comment]
Anybody has this issue or is it just me?
Error - getaddrinfo ENOTFOUND homebridge-gsh.iot.oz.nu
