### ISSUE TITLE
Cannot connect the Google Home app to Homebridge

### ISSUE THREAD

**Issue by remaskip** [oznu/homebridge-gsh#172]
**Describe Your Problem:**
I'm trying to connect my Google Home app (with 2 lights on it), but i can't connect it to my homebridge server

**Logs:**
[7/22/2022, 4:31:22 AM] [Google Smart Home] Received SYNC intent
[7/22/2022, 4:31:22 AM] [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "13404791036059370578"
    }
  ],
  "requestId": "13404791036059370578"
}
[7/22/2022, 4:31:22 AM] [Google Smart Home] No supported devices found. See https://git.io/JfuHW
[7/22/2022, 4:31:25 AM] [Google Smart Home] Sending Sync Request

**Homebridge Config:**

```json
{
    "name": "Google Smart Home",
    "token": "",
    "notice": "Keep your token a secret!",
    "disablePinCodeRequirement": true,
    "debug": true,
    "platform": "google-smarthome"
}
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/55140807/180399859-4c406711-5d25-4605-999a-148b00d307c5.png)

**Environment:**

* **Node.js Version**: v16.16.0
* **NPM Version**: 8.11.0
* **Homebridge Version**: 1.5.0
* **Homebridge GSH Plugin Version**: v2.2.0
* **Homebridge Config UI X Plugin Version**: v4.50.0
* **Operating System**: Ubuntu Focal Fossa (20.04.4 LTS) [Hyper-V]

**Comment by Dummyc0m** [comment]
I got the same error on android Google Home App. Tried iOS app and it worked.

**Comment by ewandank** [comment]
This plugin is not to add google home devices to homebridge. It is for adding homebridge devices to google home. Use the plugin for whichever manufacturer your lights are.
