### ISSUE TITLE
Server is down?

### ISSUE THREAD

**Issue by SMADdie86** [oznu/homebridge-gsh#177]
**Describe The Bug:**
The plugin triest to connect, time outs and Them tries to reconnect.
Google home States homebridge is not available.

**To Reproduce:**
Restarting modem, router etc and issues reocur after An uptime of weeks without issues.

**Expected behavior:**
Guess the later update from Google might has broken something.

* **Node.js Version**: 16.15.0
* **NPM Version**: 8.5.5
* **Homebridge Version**: 1.5.0 -V 
* **Homebridge GSH Plugin Version**: 2.2.0
* **Homebridge Config UI X Plugin Version**: 4.50.1
* **Operating System**:

**Comment by daserra23** [comment]
Also here.
