### ISSUE TITLE
Installation Issues/ Question

### ISSUE THREAD

**Issue by mike391** [oznu/homebridge-gsh#18]
Im setting up the Gsh plugin in homebridge
when I authenticate it tells me to verify that the following address is my homebridge instance:
https://192.168.2.50:8222
Is it okay that this is not a public IP? Or do I have to make my homebridge instance accessible from the outside internet?

**Comment by oznu** [comment]
Hi @mike391,

It's just a security measure, there is no need to have a public IP or homebridge accessible from the internet.
