### ISSUE TITLE
Multiple house, only one is synchronized

### ISSUE THREAD

**Issue by lacha07** [oznu/homebridge-gsh#185]
**Describe Your Problem:**
I have 2 houses and I want be able to see all devices in 2 houses in google home.
Right now I can see all devices from the first one , but nothing form the second one
Do we have a way to see both . I try to log one both homebdige instance (not in same network) without success.
I try to share the same token in all instance the 2none is receiveing event from the first ,  but I cannot see my device.

**Logs:**

**Screenshots:**

**Environment:**

* **Node.js Version**: v18.12.1 
* **NPM Version**: 
* **Homebridge Version**: 1.6.0
* **Homebridge GSH Plugin Version**: v2.2.0 
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:  Raspbian /Docker

**Comment by gileswells** [comment]
First item on the known issues list. https://github.com/oznu/homebridge-gsh#known-issues
