### ISSUE TITLE
Support for TVs

### ISSUE THREAD

**Issue by jcbshw** [oznu/homebridge-gsh#19]
Any chance of exposing homebridge TVs to google assistant?

Thanks

**Comment by oznu** [comment]
Looking at the Google Smart Home types, TV is not listed. I could probably implement this as a switch, but that would just give you on/off capabilities.

**Comment by oznu** [comment]
TV support (On/Off) has landed in v1.1.0. TV's are not yet an officially supported accessory so there is no documentation on how to add channels / volume control yet.
