### ISSUE TITLE
Homebridge Google Smart Home - Now Available

### ISSUE THREAD

**Issue by oznu** [oznu/homebridge-gsh#2]
The `homebridge-gsh` plugin will allow you to control your supported Homebridge accessories from any Google Home speaker or the Google Home mobile app.

This plugin is still in development and not ready for general use yet.

## Get Notified

To get notified when it's available, **Watch Releases** on this repo, or subscribe to this issue.

![55521767-b6a6d680-56b4-11e9-9ddf-87b7e2888153](https://user-images.githubusercontent.com/3979615/62028720-47855d00-b224-11e9-99fa-fcbf563712be.gif)

## Outstanding Tasks:

- [x] Action submitted to Google for approval (2019-07-24)
- [x] Action passed certification (2019-08-09)
- [x] Action approved by Google review team (2019-08-10)
- [x] Action deployed to Google Assistant Directory
- [x] Update documentation to show how to link the Homebridge GSH action from the Google Home app
- [x] Publish `homebridge-config-ui-x` v4.6.0

**Comment by overzero-git** [comment]
Hello! I'm interested when is you project will be released?

**Comment by oznu** [comment]
Hi @overzero-git,

The English Google Action is scheduled to go live in the Google Assistant directory on Thursday (Google pushes all new actions out the the directory once a week at this time).

Once that's live I'll start working on publishing to other regions, though I will require community help with translating a few blocks of text.

**Comment by overzero-git** [comment]
Great! I can help you translating to the Russian

**Comment by oznu** [comment]
Thanks @overzero-git,

Checkout https://github.com/oznu/homebridge-gsh/tree/master/i18n. There are only 3 phrases that should need translating.

**Comment by overzero-git** [comment]
{
  "auth0.message_consent": "Выполняя вход, вы позволяете Google получить доступ к вашим устройствам.",
  "google_action.directory.message_short_description": "Управляйте вашими устройствами Homebridge с помощью Ассистента Google.",
  "google_action.directory.message_full_description": "Вы сможете управлять аксессуарами, связанными с локальной копией Homebridge с помощью Google Ассистента."
}

**Comment by overzero-git** [comment]
Uploaded "ru.json" to the i18n folder

**Comment by sunnytoeter** [comment]
German translation:

{
  "auth0.message_consent": "Durch die Anmeldung erlauben Sie Google, auf Ihre Geräte zuzugreifen.",
  "google_action.directory.message_short_description": "Steuern Sie Ihre Homebridge Geräte mit dem Google Assistant",
  "google_action.directory.message_full_description": "Mit dem Homebridge Skill können Sie Ihre unterstützten Geräte, die mit Ihrer lokalen Homebridge Instanz verbunden sind, über den Google Assistant steuern."
}

**Comment by oznu** [comment]
https://assistant.google.com/services/a/uid/000000b558f0d5d1?hl=en

**Comment by oznu** [comment]
The Homebridge Action for Google Assistant is now live.

**Comment by overzero-git** [comment]
Oops... Something gone wrong. There is account linking issue: "couldn't update your settings".

**Comment by oznu** [comment]
Hey @overzero-git, did you restart homebridge after adding the plugin?

**Comment by overzero-git** [comment]
Yes I did. I will try to re-link Google account and restart it again

**Comment by overzero-git** [comment]
Okay, it works! Great!

**Comment by overzero-git** [comment]
Goog job, @oznu and thank you!

**Comment by daniel4099** [comment]
Not working for me :(. I’ve reinstalled plugin, relinked account. After I choose home bridge in google app it says account linked, goes to home devices but no devices appear. Also hombebridge not listed in google services. Is it possible that iOS 13 is a problem ?

**Comment by oznu** [comment]
Hi @daniel4099 - can you try with the latest update. There was an issue with the reporting of coloured bulbs that may have been causing issues. You may need to add the Homebridge Action to the Google Home app again.

**Comment by daniel4099** [comment]
Unfortunately still the same :(. Anyone tried on iOS 13 ?

**Comment by oznu** [comment]
@daniel4099,  try debug mode:

![image](https://user-images.githubusercontent.com/3979615/63135274-867f2500-c010-11e9-8d06-2ea7608df8de.png)

I don't think your instance is discovering any devices for some reason.

```json
{
     "requestId": "6145848850313323247",
     "payload": {
         "agentUserId": "xxxxxxxxxxxxxxx",
         "devices": []
     }
 }
```

**Comment by daniel4099** [comment]
Ok, will do have can I check and provide you the log ?

**Comment by oznu** [comment]
Hey @daniel4099, yep please do. Please raise a new issue with the details (use the issue template provided).
