### ISSUE TITLE
Auth error

### ISSUE THREAD

**Issue by Drun555** [oznu/homebridge-gsh#20]
![image](https://user-images.githubusercontent.com/44411820/69899920-5c1a6300-1386-11ea-854d-d1b6443c39c2.png)

I'm pretty sure my connection is clean. Isn't it the problem on your side?

Happens only with Google authentication. With github all is working properly.

**Comment by oznu** [comment]
Can you email me the username of the account you are using the sign in with?

My email can be found in [my profile](https://github.com/oznu).
