### ISSUE TITLE
Google Home App, doesn't show any devices, if not connected to local Network

### ISSUE THREAD

**Issue by gsiscotty** [oznu/homebridge-gsh#21]
While not connected to my local Network, i don't see any devices in my google home app.
Is there a way, to use GSH without a local Network connection?

**Comment by oznu** [comment]
All actions performed in the Google Home app go via Google's servers regardless of whether or not you're on your local network.

**Comment by gsiscotty** [comment]
Thank you for the response.
The Logs, don't show anything problematic.

Any idea, where i should start looking for possible issues? (or just, reinstall the plugin?)


thx for advice

**Comment by oznu** [comment]
Do your other Google Home devices show up when using an external network? Does it happen on all external networks?

**Comment by gsiscotty** [comment]
The most of my Google Home devices, are integrated via homebridge (gsh plugin).
There are only 2 other devices, (irobot roomba and chromecast), wich are directly integrated.

They work wherever i am (and connected to).

Only the ones, discovered by the gsh pluging don't show up.. 
No i'm connected to the home network and they don't show up neither.
So currently, i don't see any devices from gsh at all.

**Comment by oznu** [comment]
Email me your username / email that you've used to connect with - address in my profile.

Then drop off WiFi and attempt to sync devices (pull down in the Google Home app). Once you've done this a few times reply back here and I'll check the logs.

**Comment by gsiscotty** [comment]
thx, tried a view times to update my home app.
hope you find something

**Comment by oznu** [comment]
I'm not seeing anything come through from Google's side for your account, I can see your homebridge instance is connected though.

Can you try removing the action from the Google Home app and re-adding it?

From the Google Home app:

1. Add
2. Set up a device
3. Have something already setup?
4. Click the "Homebridge" action at the top of the page, and selected "Unlink"

**Comment by gsiscotty** [comment]
Ok, now i think i see why it happened.

The Google Home App, lost its connection to the Homebridge (just the
"Device") i reconnected the Homebridge, not its back again.


Going to test everything.

Will send you an update.


Am Mi., 4. Dez. 2019 um 00:11 Uhr schrieb oznu <notifications@github.com>:

**Comment by gsiscotty** [comment]
After completely removing the Link, and reconnecting the link, i'm seeing my devices again.

Thank you for the Support!
