### ISSUE TITLE
Google Home devices not responding 

### ISSUE THREAD

**Issue by jcbshw** [oznu/homebridge-gsh#22]
About a week ago devices started not responding in google home almost once a day. Only solution I’ve found is restarting homebridge. Nothing has changed in my config or plugins added. Nothing in the log file either.

**Comment by oznu** [comment]
Hi @jcbshw,

Email me the username of the account you used to connect Homebridge and I'll check the logs on my end. You can find my email address in my GitHub profile.

**Comment by jcbshw** [comment]
@oznu done!

**Comment by oznu** [comment]
Thanks @jcbshw.

I've reviewed the logs and can see a potential issue worth investigating. I'll take a deeper look this weekend.

**Comment by oznu** [comment]
@jcbshw - I pushed up a small change I think might fix this, can you let me know how it goes over the next few days?

**Comment by jcbshw** [comment]
@oznu thanks! Will do.

**Comment by jcbshw** [comment]
@oznu seems like what you did fixed it. Haven’t had an instance of my devices not responding in Google Home since.

**Comment by oznu** [comment]
Great, thanks for letting me know.
