### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by meluvalli** [oznu/homebridge-gsh#25]
I have noticed on my iOS devices, i'll get "Devices Not Responding" or "Updating" for 10-30 seconds.  I thought it was an issue with HomeBridge-HomeSeer-2018 plugin, but I realized that it actually seems to happen (at least a lot more often) when I have this plugin installed.

It's not only this plugin that causes it.  I also have used the homebridge-alexa plugin and it also causes issues with speed.

If I strictly have ONLY the HomeBridge-HomeSeer plugin installed, everything seems REALLY fast.

Have you heard of this or know of any resolutions to try?  I will also post this on the HomeBridge-HomeSeer github just for there feedback as well.

**Comment by oznu** [comment]
Hi @meluvalli,

Based on the comment on your other issue can this be closed?

**Comment by meluvalli** [comment]
Yes.  Will close for now :)
