### ISSUE TITLE
Settings don't hold on Google

### ISSUE THREAD

**Issue by meluvalli** [oznu/homebridge-gsh#27]
After logging into Google Home and assigning all my devices to a room and naming them correctly, later my devices reset on Google and everything is back as if I just added the devices again.

Is this normal?  Is there anyway of preventing this?  

It's like the device ID's change or something because I can't rename them back to what they were because google thinks the device is still there, but I can't see it anymore.  I have to delete the home on Google and recreate it.

**Comment by oznu** [comment]
If you ever delete your Homebridge accessories/persist or change the Homebridge username in the `config.json` the device IDs will change in Google Home.

Looking at your logs I can see your instance username changed a few times over the last few days (my logs [only show a sha256 hash of the username](https://github.com/oznu/homebridge-gsh/blob/master/src/main.ts#L19-L22), I don't know the actual usernames being used).

Changes I can see:

```
Dec 20 00:30:47 Client Connected: 7c68c2a9d53fb0c5e8baa438bbc004216e7a90b08ed3277d37fefd7ca944fbf1
Dec 20 01:25:44 Client Connected: 7683fc72bc56cbcc0b474ec01020bfecbd7f63e7c5b5c57adaa7c7ae8b7df014
```

```
Dec 20 05:17:37 Client Connected: 7683fc72bc56cbcc0b474ec01020bfecbd7f63e7c5b5c57adaa7c7ae8b7df014
Dec 20 05:19:44 Client Connected: 48b4c15c2b93648c405aebb9cbdf3479a2c4e33acb537d3926a3f21b186e8b0f
```

```
Dec 20 18:16:02 Client Connected: 3c5d70e2e25d5ad1fe1c7b465d49fa4d0b4a3cd3a5028111eda9001ebc9e459a
Dec 20 19:27:54 Client Connected: 060d344dd255513263f25f367e41d234c95a80d916c446364ff171c002166715
```

```
Dec 21 18:21:49 Client Connected: 060d344dd255513263f25f367e41d234c95a80d916c446364ff171c002166715
Dec 21 18:40:09 Client Connected: 7c68c2a9d53fb0c5e8baa438bbc004216e7a90b08ed3277d37fefd7ca944fbf1
```

```
Dec 21 19:45:57 Client Connected: 7c68c2a9d53fb0c5e8baa438bbc004216e7a90b08ed3277d37fefd7ca944fbf1
Dec 21 19:58:39 Client Connected: 060d344dd255513263f25f367e41d234c95a80d916c446364ff171c002166715
```

**Comment by meluvalli** [comment]
Got it.  That explains yesterday's change, but not todays.  I haven't changed the username and/or deleted the persist folder at all today.   I will keep an eye on it and let you know if it's still happening.  I have been changing the config file a lot, but just the "host" under HomeSeer platform.  I wouldn't think this would cause this :(

**Comment by oznu** [comment]
If the HomeSeer platform is creating a new instance of the accessory it will also get a new ID in Google Home.

Can you confirm you are only running the Homebridge GSH plugin on a single instance on your network?

**Comment by meluvalli** [comment]
Yes.  I can confirm this.  I also only run node with -I on the one instance as well.

**Comment by meluvalli** [comment]
I did just block the username of the second instance in settings as suggested in issue #26
