### ISSUE TITLE
Impossible to associate with Google Home

### ISSUE THREAD

**Issue by JeromeB28** [oznu/homebridge-gsh#28]
Dear Oznu,

Here is my issue. Hope you can help me.

On my android phone, I opened Google Home app.
Then I clicked on "Add Device", then "Set up device", then "gave something already setup", then I choose "Homebridge" then I log in with Google.
It answered : connexion then "Association of my account to Homebridge" then I went back to previous screen and nothing has been associated :(

Thank you in advance for your help.

**Logs:**

[07/01/2020, 13:02:55] Homebridge is running on port 51826.
[07/01/2020, 13:02:55] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[07/01/2020, 13:03:05] [Config] Homebridge Config UI X v4.6.7 is listening on :: port 8080
  hapNodeJSClient Starting Homebridge instance discovery +0ms
  hapNodeJSClient HAP Device discovered BSB002 [ 'fe80::217:88ff:fe40:9ab5', '192.168.1.11' ] +150ms
  hapNodeJSClient HAP instance address: BSB002 -> Philips-hue.local -> 192.168.1.11:8080 +27ms
  hapNodeJSClient HAP Discover failed BSB002 http://192.168.1.11:8080 error code 470 +91ms
  hapNodeJSClient HAP Device discovered Healthy Home Coach [ '192.168.1.22', 'fe80::72ee:50ff:fe26:1390' ] +137ms
  hapNodeJSClient HAP instance address: Healthy Home Coach -> Healthy Home Coach.local -> 192.168.1.22:5001 +1ms
  hapNodeJSClient HAP Discover failed Healthy Home Coach http://192.168.1.22:5001 error code 470 +26ms
  hapNodeJSClient HAP Device discovered Homebridge [ '192.168.1.75',
  '2a01:cb1c:184:700:1ae4:40ec:f3db:96f1',
  'fe80::e66a:d5bd:2844:426b' ] +2s
  hapNodeJSClient HAP instance address: Homebridge -> CC_22_3D_E3_CE_21.local -> 192.168.1.75:51826 +1ms
  hapNodeJSClient Homebridge instance discovered Homebridge-6279 with 5 accessories +45ms
  hapNodeJSClient Ending Homebridge instance discovery +8s
[07/01/2020, 13:03:19] [Google Smart Home] Finished instance discovery
[07/01/2020, 13:03:34] [Google Smart Home] Sending Sync Request
[07/01/2020, 13:03:43] [Google Smart Home] Received SYNC intent
[07/01/2020, 13:03:43] [Google Smart Home] {
  "inputs": [
    {
      "intent": "action.devices.SYNC",
      "requestId": "4587449935825669676"
    }
  ],
  "requestId": "4587449935825669676"
}
[07/01/2020, 13:03:43] [Google Smart Home] []
[07/01/2020, 13:03:53] [Google Smart Home] Sending full post-sync state report

**Homebridge Config:**

{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:21",
        "port": 51826,
        "pin": "131-45-154"
    },
    "platforms": [
        {
            "platform": "config",
            "name": "Config",
            "port": 8080,
            "sudo": true
        },
        {
            "platform": "netatmo",
            "name": "netatmo platform",
            "ttl": 5,
            "auth": {
                "client_id": "XXXXXX",
                "client_secret": "XXXXXXX",
                "username": "XXXXX.XXXXX@gmail.com",
                "password": "XXXXXX*"
            }
        },
        {
            "name": "Google Smart Home",
            "token": XXXXXXXX",
            "notice": "Keep your token a secret!",
            "debug": true,
            "platform": "google-smarthome"
        }
    ],
    "accessories": []
}

**Screenshots:**

[drive-download-20200107T125539Z-001.zip](https://github.com/oznu/homebridge-gsh/files/4030725/drive-download-20200107T125539Z-001.zip)

**Environment:**

* **Node.js Version**: v10.15.2
* **NPM Version**: 6.13.4
* **Homebridge Version**: 0.4.50
* **Homebridge GSH Plugin Version**: v1.1.3
* **Homebridge Config UI X Plugin Version**: v4.6.7
* **Operating System**: Debian on Raspberry Pi 3

**Comment by oznu** [comment]
Hi @JeromeB28,

What sort of accessories do you have setup via your Homebridge instance?

**Comment by JeromeB28** [comment]
Hi Oznu,

For the moment, I've only setup a netatmo temperature & humidity sensor
(for info, the sensor is working well with ios homekit).

Thank you in advance for your support.

**Comment by oznu** [comment]
Hi @JeromeB28,

The Google Smart Home service doesn't support sensor device types at the moment. See https://github.com/oznu/homebridge-gsh#supported-device-types for a full list of device types.

**Comment by JeromeB28** [comment]
Thanks a lot for your answer.
Do you plan to implement sensor management in a close future ?

**Comment by oznu** [comment]
Hi @JeromeB28,

Once the Google Smart Home API supports it, I will implement it here.

**Comment by JeromeB28** [comment]
Thank you for your response.
Yesterday I googled it and I started to understand that's indeed the
problem is coming from google API. So you confirm the issue ;-)

I understood also that Alexa is more compatible with sensors. But I haven't
any Amazon Alexa device for testing.
Did you have the chance to test it with Alexa ?
