### ISSUE TITLE
Security System

### ISSUE THREAD

**Issue by mikemelga** [oznu/homebridge-gsh#29]
Hi.

Any chance of adding support for Security System device type?
It is already a device present in Google Smart Home and behaves a little different from switches because it asks for confirmation on certain sensible actions.

Thanks.

**Comment by skitzow88** [comment]
You can add the dummy lock feature within homebridge. With some automation you can get that acting as a security system within google home.

**Comment by oznu** [comment]
I'll add this at some point, it shouldn't be to hard. Two factor will be required (verbal pin).

**Comment by skitzow88** [comment]
Contact sensors would be ideal to! :)

**Comment by oznu** [comment]
Unfortunately Google "Smart Home" actions do not support sensors at this time. The full list of possible supported device types is listed here: 

https://developers.google.com/assistant/smarthome/guides

**Comment by skitzow88** [comment]
aaah thats a bummer! Thanks for sharing the information!

**Comment by oznu** [comment]
* Added support for Security System accessory types ([#29](https://github.com/oznu/homebridge-gsh/issues/29))
  * *OK Google, set the security system to Home*
  * *OK Google, set the security system to Night*
  * *OK Google, set the security system to Away*
  * *OK Google, set the security system to Off*
* A Two Factor Authentication pin must be set for Lock Mechanisms and Security Systems to be exposed to Google Home. You can set your pin in the Homebridge Google Home plugin settings.
