### ISSUE TITLE
Doors and windows not displayed

### ISSUE THREAD

**Issue by sunnytoeter** [oznu/homebridge-gsh#30]
Hello,

 I am using homebridge with this plugin, so far Lights and Thermostats are visible in the google home app. I do have however several shutter contacts on my doors and windows. None of them is visible in the app.
When configuring them as "motorized windows" in homebridge, I can at least see them, but not any state. I have only a static icon without any chance of seeing weather the shutter contact is open or closed. Of course everything works as expected in homekit and also in homebridge-config-ui-x. There I can see the state of the doors and windows.
Also my door lock is only displayed with a gear icon, but cannot be used to open or close the lock from google. 

any hints?

thank you and best

**Comment by oznu** [comment]
Have you tried using voice commands? The google Home app only allows visual control of a small number of accessory types.

**Comment by sunnytoeter** [comment]
Hello,

 when I ask google "are any windows open", there are two possibilties:

1) all windows are closed: google assistant answers "all 12 windows are closed".
2) one ore more windows open: google assistant does not reply but opens the home app - and displays nothing. No feedback on which window could be open.

all this for "motorized windows". 
When using default window configuration, nothing happens at all.

**Comment by oznu** [comment]
Does asking Google to open or close the window work?

For example, "ok google, open the bedroom window" or "ok google, open the bedroom window to 50%"?

**Comment by sunnytoeter** [comment]
No, this does not work either (it does not even try to do so, but this could be related to the fact that this are only shutter contacts and not real motorized windows).

**Comment by oznu** [comment]
Ok what about asking for the status of a single window?

eg. "ok google, is the bedroom window open?"

**Comment by sunnytoeter** [comment]
It then also tried to open the home app - and shows nothing. No voice rely. really strange.

**Comment by sunnytoeter** [comment]
I an giving up with google home, it is far from homekit comfort... I just close the ticket for now.
