### ISSUE TITLE
Unable to add additional Homebridge Action devices

### ISSUE THREAD

**Issue by dnicolson** [oznu/homebridge-gsh#31]
**Describe The Bug:**

Homebridge does not appear when setting up a device in the Google Home app. Tapping the existing Homebridge item and selecting "Check for new devices" results in a "Homebridge is linked" message followed by a "Something went wrong. Try again" message. I have unlinked and linked the the account but the result is the same.

**To Reproduce:**

1. Set up device
2. Select "Have something already set up?"
3. Search for "Homebridge"

**Expected behavior:**

Homebridge to appear when searching or "Check for new devices" to work without an error.

**Logs:**

```
[2/17/2020, 18:42:19] [Google Smart Home] Initializing google-smarthome platform...
[2/17/2020, 18:42:21] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[2/17/2020, 18:42:45] [Google Smart Home] Finished instance discovery
[2/17/2020, 18:43:00] [Google Smart Home] Sending Sync Request
```

**Homebridge Config:**

```json
{
            "name": "Google Smart Home",
            "token": "",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome"
}
```

**Screenshots:**

![IMG_6702](https://user-images.githubusercontent.com/2276355/74683558-a4009780-51c9-11ea-80fd-d16f56f9e0f4.png)

**Environment:**

* **Node.js Version**: 12.15.0
* **NPM Version**: 6.13.7
* **Homebridge Version**: 0.4.50
* **Homebridge GSH Plugin Version**: 1.1.4
* **Homebridge Config UI X Plugin Version**: 4.10.1
* **Operating System**: Raspbian Buster Lite (2020-02-05)

**Comment by oznu** [comment]
Make sure you've logged into the Google Action with the same account you connected the Google Home plugin with in Homebridge Config UI X.

You can only have one instance of Homebridge connected per Home - see https://github.com/oznu/homebridge-gsh#multiple-homebridge-instances

If you're still facing issues please enable debug mode, restart, and post the logs for the first 1-2 minutes of Homebridge being online:

![image](https://user-images.githubusercontent.com/3979615/64935403-70c18180-d894-11e9-96e4-78efb744730c.png)

**Comment by dnicolson** [comment]
Running `sudo hb-service stop` and then `homebridge -I -U /var/lib/homebridge/` seems to have resolved the issue. This is strange as the same arguments exist as `HOMEBRIDGE_OPTS` in the file `/etc/default/homebridge`, so there may be other factors involved.

The logs contained several instances of `Operation not permitted` errors in other modules and `EACCES: permission denied, open '/var/lib/homebridge/accessories/cachedAccessories'` errors.
