### ISSUE TITLE
Issue sending command to connected homebridge

### ISSUE THREAD

**Issue by shanelilley** [oznu/homebridge-gsh#32]
Hi - I am unable to control any homebridge device from Google Home. I have a Google Next Mini speaker hooked in to Google Home via the App. I have set up a single RPi with the plugin and I believe I have linked it correctly to my google account. I have also added the necessary Google/Homebridge assistant piece. 

The logs below show -

** Login appears to be successful - 
[2020-2-21 10:33:34] Homebridge is running on port 51826.
[2020-2-21 10:33:50] [Google Smart Home] Waiting 15 seconds before starting instance discovery...
[2020-2-21 10:33:52] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[2020-2-21 10:34:15] [Google Smart Home] Finished instance discovery
[2020-2-21 10:34:16] [Google Smart Home] HAP Event listeners registered succesfully
[2020-2-21 10:34:30] [Google Smart Home] Sending Sync Request

** Sending device status (I have a single gpio relay switch as a test) -
[2020-2-21 10:42:49] [Google Smart Home] Sending State Report
[2020-2-21 10:42:49] [Google Smart Home] {
  "type": "report-state",
  "body": {
    "dbf71b56e88cfcd828e17a7655c4fe86a96f0ea7ccf6de168422e953d4ea6c22": {
      "on": false,
      "online": true
    }
  }
}

[2020-2-21 10:45:00] [Google Smart Home] Sending State Report
[2020-2-21 10:45:00] [Google Smart Home] {
  "type": "report-state",
  "body": {
    "dbf71b56e88cfcd828e17a7655c4fe86a96f0ea7ccf6de168422e953d4ea6c22": {
      "on": true,
      "online": true
    }
  }
}

config.json  -
        {
            "name": "Google Smart Home",
            "token": "<removed>",
            "notice": "Keep your token a secret!",
            "debug": true,
            "platform": "google-smarthome"
        }

config.json - pgio device config - 

        {
            "accessory": "GPIODevice",
            "type": "Lightbulb",
            "name": "Sample Lights",
            "inverted": true,
            "pin": 24
        }

My understanding is that I should be able to say "Hey google, switch on SAMPLE LIGHTS" ? Or have I misunderstood the purpose of the plugin?

Environment - 
Raspian Stretch
homebridge-gsh v1.1.4
Node v9.9.0

**Comment by oznu** [comment]
Hi @shanelilley,

Have you added the Homebridge action in the Google Home app?

https://github.com/oznu/homebridge-gsh/wiki#add-homebridge-to-google-home-app

**Comment by shanelilley** [comment]
I had trouble linking the Homebridge piece in Google App.

**Comment by shanelilley** [comment]
@oznu - many thanks, yes, that was my issue. I thought I had done this. All fixed now. thanks so much for your reply.
