### ISSUE TITLE
2FA only for sensitive actions in security systems

### ISSUE THREAD

**Issue by bktz** [oznu/homebridge-gsh#36]
**Is your feature request related to a problem? Please describe:**
I need to announce my 2FA code to set the security system state to away, home, or night.

**Describe the solution you'd like:**
 I am looking to use the google home to set my security system state to away, home or night (from the off state) without requiring 2FA. This is not a sensitive action so it shouldn't require a 2FA passcode to be performed.

**Describe alternatives you've considered:**
Currently my alternative is to use siri on my phone to change the security system state so that I do not need to announce my 2FA passcode.

**Additional context:**
According to [https://developers.google.com/assistant/smarthome/guides/securitysystem#request](https://developers.google.com/assistant/smarthome/guides/securitysystem#request) only disarming the security system is a sensitive action & the rest are not so I believe the google assistant API should support this action as well.

**Comment by bktz** [comment]
I believe this can be accomplished by updating the is2faRequired function found here:
https://github.com/oznu/homebridge-gsh/blob/c45d16516276bcabeb5c3a6750933f25f5047dd0/src/types/security-system.ts#L142

**Comment by oznu** [comment]
Landing in 1.3.0. Thanks!
