### ISSUE TITLE
Exclude some accessories

### ISSUE THREAD

**Issue by matijus91** [oznu/homebridge-gsh#39]
Some of my homebridge plugins I use aren't compatible for homekit but they can be ad to Google home. So is there a way to exclude some types? For example Locks en Windowcovering. So they do not ad to my Google Home because they already there.

**Comment by oznu** [comment]
Under Advanced Settings:

![image](https://user-images.githubusercontent.com/3979615/79196982-5a07fb00-7e74-11ea-8007-143194333b58.png)

**Comment by matijus91** [comment]
Only see this...

![Schermafbeelding 2020-04-14 om 09 42 03](https://user-images.githubusercontent.com/31914336/79198740-42a91d80-7e34-11ea-9eaa-c26e5de4292e.png)

**Comment by oznu** [comment]
Please raise an issue over here: https://github.com/hoobs-org/homebridge-google

**Comment by oznu** [comment]
You can manually add it to the config:

```json
            "accessoryFilter": [
                "Accessory Name Here",
                "Another Name Here"
            ]
```

However manual editing of the config.json is not something I support for this plugin.
