### ISSUE TITLE
Google Smart Home Unlinking in App

### ISSUE THREAD

**Issue by thehauntedmattress** [oznu/homebridge-gsh#40]
I've noticed that sometimes when I reboot my Raspberry Pi, the Google Home app says that my gmail account has unlinked all of my homebridge devices.  Is there a solution to this?  Thanks.

**Comment by thehauntedmattress** [comment]
Not stale.

**Comment by A-Dorian** [comment]
Hello,
it happens to me too but without restarting y raspberry.
After a few time, Homebridge seems to lose the connection with google :
`[5/18/2020, 3:24:34 PM] [Google Smart Home] Lost Connection (1) - No ping back for 20100ms`
`[5/18/2020, 3:24:34 PM] [Google Smart Home] Disconnected (1) - Retry in 5000ms`
`[5/18/2020, 3:24:39 PM] [Google Smart Home] Reconnecting (1)`
`[5/18/2020, 3:24:59 PM] [Google Smart Home] Error (2) - getaddrinfo EAI_AGAIN homebridge-gsh.iot.oz.nu`
`[5/18/2020, 3:24:59 PM] [Google Smart Home] Disconnected (2) - Retry in 5000ms`

And after a few time arrived to reconnect:
`[5/18/2020, 3:27:30 PM] [Google Smart Home] Connected (11) - wss://homebridge-gsh.iot.oz.nu`

However, when I use my google assistant, it answers me that it can't communicate with Homebridge.
`[5/18/2020, 9:49:29 PM] [Google Smart Home] Received EXECUTE intent`
`[5/18/2020, 9:52:48 PM] [Google Smart Home] Received EXECUTE intent`
`[5/18/2020, 9:53:17 PM] [Google Smart Home] Received QUERY intent`

I need to restart Homebridge each time it's happened to fix the issue. Happens every day...

**Comment by thehauntedmattress** [comment]
So I wrote this before I realized it but I think the issue happens when the Google Home is restarted, not the Raspberry Pi.

**Comment by A-Dorian** [comment]
In my case, I don't observe any raspberry/Google home restart...

**Comment by oznu** [comment]
> I've noticed that sometimes when I reboot my Raspberry Pi, the Google Home app says that my gmail account has unlinked all of my homebridge devices. Is there a solution to this? Thanks.

@thehauntedmattress  this should be fixed in 1.4.2.

**Comment by thehauntedmattress** [comment]
@oznu I will update and play with it.  Thank you for your support!
