### ISSUE TITLE
I'm just wondering when this will be fixed?

### ISSUE THREAD

**Issue by treforparr** [oznu/homebridge-gsh#44]
I really would like an update on when this will be fixed on the hoobs, I'm just wondering if the developer could get back to us to let me know what's going on and how far they are and fixing the problem in hoobs and if they have a timescale, I really wanna test out with HomeKit what I was going to ask as well as the picture I really wanna see bringing ring doorbell  in Googlehome  network

**Comment by donavanbecker** [comment]
This is a plugin for homebridge, not for hoobs. If you are having issues, I would think about potentially switching to original homebridge.
