### ISSUE TITLE
Can't authorize with Google Home App

### ISSUE THREAD

**Issue by patrickhopman** [oznu/homebridge-gsh#50]
I've connected my account via the Homebridge Config UI settings for the plugin. When i try to connect it via the google home app and i choose for homebridge in the services, it says account connected. After a few seconds it gives an error and its not connected.

What to do to authorize it?

**Comment by Q660S** [comment]
This also happens to me with other services. It might be a problem with the google home app instead of the plugin. Last time this happened to me I think it was either a phone restart or app reinstall that solved it.
