### ISSUE TITLE
I'm interested in implementing camera support

### ISSUE THREAD

**Issue by SheaSmith** [oznu/homebridge-gsh#54]
I noticed that camera support was requested in #16, which is something that I am also interested in having. As I am relatively familiar with TypeScript, I thought I might be able to give it a crack, however, I'd like to have a discussion around the best way to implement this.

My thoughts are to add the ability, in a configuration file, to run some sort of shell script (e.g. that calls FFMPEG) that outputs HLS to a web server (the address of which is also specified in the configuration). From looking at the Google Developer documentation, it should simply be a matter of inputting the URL to that particular stream. 

The main obstacle with this method as far as I can tell would be remote access, as we would likely have to port forward in order to access streams remotely because even if there was some way to stream it through the current central server setup, I'd imagine that would be rather bandwidth heavy.

The other thing that would need to be sorted would be the ability to have some sort of per-device configuration. I suppose this could be avoided by having a global script that we pass the RTSP stream and the accessory ID to, and then we do something like this for the webserver portion: `{webserverurl}/{accessory_id}/index.m3u8`, but this seems like a rather hacky way of doing this.

**Comment by oznu** [comment]
Hi @SheaSmith,

If you want to have a go at this feel free. Perhaps the easiest way would be to just allow users to provide their own compatible stream url? Then they can work out the port forwarding and ffmpeg (if required).

**Comment by SheaSmith** [comment]
My thoughts with having a start script means that they would be able to have the streams start/stop on demand, rather than taking up resources transcoding needlessly (which if you have a few cameras could be problematic). But yes, the port forwarding and web server stuff will definitely have to be left to the user.
