### ISSUE TITLE
Map rotation speed characteristic for fan service

### ISSUE THREAD

**Issue by torandreroland** [oznu/homebridge-gsh#58]
**Is your feature request related to a problem? Please describe:**
Fan services in Homekit are only exposed with an option to turn on/off in Google Smart Home.

**Describe the solution you'd like:**
Map characterstic rotation speed as well.

**Describe alternatives you've considered:**
Obviously other charactertics would be welcome as well.

**Comment by pfn** [comment]
Hmm, would be nice to reopen this, it is still an issue.
