### ISSUE TITLE
Two Factor Authentication for Garage Doors

### ISSUE THREAD

**Issue by tsviper** [oznu/homebridge-gsh#62]
**Is your feature request related to a problem? Please describe:**
I love the Two Factor Authentication for locks but it doesn't seem to apply to garage door openers.

**Describe the solution you'd like:**
Prompt for the Two Factor Authentication PIN when trying to OPEN the garage door and not when closing the door.  Just like the locks work.

**Comment by oznu** [comment]
2FA will be required to expose garage doors in the next release. The pin will only be required when opening the door.
