### ISSUE TITLE
Garage Opener Not Exposed to GA

### ISSUE THREAD

**Issue by brn2prgrm** [oznu/homebridge-gsh#7]
I have an Insignia HomeKit Garage Door opener that I was hoping to use with this plug-in.  Initially H-GHS did not seem to expose the device to my Google Assistant setup, so I re-ran my installation in debug mode.  Below seems to be the gist of my startup, and my device in question is the 'NS-CH1XGO8' on IP 192.168.7.78.  It seems to be discovered, but then fails with error code 470.  Any idea what could be wrong?  It seems I have a few devices failing with error 470.  Let me know what else I can provide to help! Thanks!

> hapNodeJSClient Starting Homebridge instance discovery +0ms
>   hapNodeJSClient HAP Device discovered BSB002 [ '192.168.7.54', 'fe80::217:88ff:fe21:843a' ] +228ms
>   hapNodeJSClient HAP instance address: BSB002 -> mikeHue.local -> 192.168.7.54:8080 +1ms
>   hapNodeJSClient HAP Device discovered LIFX Pls BR30 [ '192.168.7.45', 'fe80::d273:d5ff:fe22:3b76' ] +10ms
>   hapNodeJSClient HAP instance address: LIFX Pls BR30 -> Garage-2.local -> 192.168.7.45:80 +0ms
>   hapNodeJSClient HAP Device discovered NS-CH1XGO8 [ '192.168.7.78', 'fe80::2aed:e0ff:fe20:d62' ] +1ms
>   hapNodeJSClient HAP instance address: NS-CH1XGO8 -> GarageOpener-200D62.local -> 192.168.7.78:80 +0ms
>   hapNodeJSClient HAP Device discovered Wemo Mini [ '192.168.7.77', 'fe80::26f5:a2ff:fe94:3747' ] +1ms
>   hapNodeJSClient HAP instance address: Wemo Mini -> wemo_mini.local -> 192.168.7.77:53772 +0ms
>   hapNodeJSClient HAP Device discovered NL22 [ '192.168.7.80', 'fe80::255:daff:fe52:a1cc' ] +1ms
>   hapNodeJSClient HAP instance address: NL22 -> Light-Panels-52-a1-cc.local -> 192.168.7.80:6517 +0ms
>   hapNodeJSClient HAP Device discovered IDEV0004 [ '192.168.7.101' ] +1ms
>   hapNodeJSClient HAP instance address: IDEV0004 -> idevices-outdoor-switch.local -> 192.168.7.101:80 +0ms
>   hapNodeJSClient HAP Device discovered IDEV0009 [ '192.168.7.105' ] +1ms
>   hapNodeJSClient HAP instance address: IDEV0009 -> Wall-Dimmer-00537750.local -> 192.168.7.105:80 +0ms
>   hapNodeJSClient HAP Device discovered LIFX BR30 [ '192.168.7.46', 'fe80::d273:d5ff:fe22:55e8' ] +1ms
>   hapNodeJSClient HAP instance address: LIFX BR30 -> Garage-1.local -> 192.168.7.46:80 +0ms
>   hapNodeJSClient HAP Discover failed BSB002 http://192.168.7.54:8080 error code 470 +14ms
>   hapNodeJSClient HAP Discover failed IDEV0009 http://192.168.7.105:80 error code 470 +1ms
>   hapNodeJSClient HAP Discover failed Wemo Mini http://192.168.7.77:53772 error code 470 +6ms
>   hapNodeJSClient HAP Discover failed IDEV0004 http://192.168.7.101:80 error code 470 +10ms
>   hapNodeJSClient HAP Discover failed NS-CH1XGO8 http://192.168.7.78:80 error code 470 +9ms
>   hapNodeJSClient HAP Discover failed NL22 http://192.168.7.80:6517 error code 470 +52ms
>   hapNodeJSClient Ending Homebridge instance discovery +10s

**Comment by oznu** [comment]
Are these real HoneKit devices (i.e. not via Homebridge)?

**Comment by brn2prgrm** [comment]
Yes, all the devices that are throwing errors are true HomeKit devices.  Speaking just about my Garage Door Opener, it is a HomeKit device which is fully accessible without HomeBridge.

The device I have is: https://www.bestbuy.com/site/insignia-wi-fi-garage-door-controller-for-apple-homekit-white/5933701.p?skuId=5933701

**Comment by oznu** [comment]
That explains why it's not working. This plugin will only expose devices that are based on Homebridge or HAP-Nodejs running in insecure mode. Native HomeKit accessories aren't supported as it's not possible to communicate with them after they have been securely paired with your Apple devices.

**Comment by brn2prgrm** [comment]
Ahh derp, makes total sense, I wasn't thinking...  Thank you for the quick responses and your work on this awesome plug-in!
