### ISSUE TITLE
accessoryFilter Doesn't Work With Some Names

### ISSUE THREAD

**Issue by maxexcloo** [oznu/homebridge-gsh#72]
**Describe The Bug:**
When using some names in accessory filter, they still show up in Google Home.

**To Reproduce:**
Try to filter a name with a special character (such as `'`), for example "Max's Room Lamp".

**Expected behavior:**
Accessory does not show up in Google Home.

**Homebridge Config:**

```json
        {
            "platform": "google-smarthome",
            "plugin_map": {
                "plugin_name": "homebridge-gsh"
            },
            "name": "Google Home",
            "notice": "Keep your token a secret!",
            "token": "",
            "accessoryFilter": [
                "Living Room Fairy Lights",
                "Living Room Lava Lamp",
                "Living Room Smart Kettle",
                "Max's Room Lava Lamp"
            ]
        },
```

**Environment:**

* **Node.js Version**: v12.16.2
* **NPM Version**: 6.14.4
* **Homebridge Version**: v1.2.0
* **Homebridge GSH Plugin Version**:  1.6.0
* **Homebridge Config UI X Plugin Version**: N/A
* **Operating System**: Docker

**Comment by gitunit** [comment]
for me, no filter actually worked until i hit "reconnect account" in google home.

**Comment by maxexcloo** [comment]
It hasn't been fixed yet?

**Comment by maxexcloo** [comment]
I'll close this as I haven't been able to solve it - not sure why it's not working!
