### ISSUE TITLE
Garage Door Security via Google Home

### ISSUE THREAD

**Issue by cheitzig** [oznu/homebridge-gsh#76]
**Is your feature request related to a problem? Please describe:**

I have a Garage Door Opener (GDO) integrated with Homekit via the homebridge and homebridge-myq projects. I'm just installed homebridge-gsh, but realize there's a security hole once I have the garage doors accessible via Google Home-- a burgler could conceivably yell through even a closed window "Hey Google, open the garage door", and my garage door would open.
**Describe the solution you'd like:**

When the garage door is requested to open, perhaps a PIN could be requested?
**Describe alternatives you've considered:**

I'm happy to help think this through and even code it up. I'm not sure where the feature should be implemented though... it's not obvious whether it should be on homebridge-myq or on homebridge-gsh.
**Additional context:**

A few additional thoughts
- Homekit seems to require authentication (on the phone/ipad/etc.) before opening the door, while the Google Home does not.
- The MyQ integration that's integrated through the Google Home seems to allow closing the door, but not opening "for security reasons"

Note: I posted a similar issue on the homebridge-gsh github, because I'm not sure where / how this should / could be considered.

**Comment by cheitzig** [comment]
I realized after looking through the code a bit that it looks like it's a question of adding two factor authentication to the garage door type. That's looks straight-forward-ish... I'm happy to help / code something up, but think I need some guidance.

**Comment by oznu** [comment]
2FA will be required to expose garage doors in the next release.

**Comment by cheitzig** [comment]
Fantastic! Thanks, Oznu. Is there any way I can help?
