### ISSUE TITLE
Support for UniFi Protect Cams / doorbell / homebridge

### ISSUE THREAD

**Issue by mbnn** [oznu/homebridge-gsh#78]
Hello there,

Thank you for this amazing plugin.
I mostly use homebridge because of the UniFi Protect plugin: https://github.com/hjdhjd/homebridge-unifi-protect
That works like a charm in homekit. However, now i wanted to see if I could add this plugin to get the UniFi G4 doorbell also working in Google Home (so i can let the sonos speakers ring when someone uses the doorbell). Would it be possible to add this?

Right now it says: No supported devices found.

**Comment by oznu** [comment]
Google Smart Home presently doesn't have support for 3rd party doorbell integrations - it looks like this is coming soon based on some leaks, so once it's available I'll do it.

**Comment by oznu** [comment]
I probably won't ever do cameras, but doorbell notifications to your smart speaker should be possible based on the leaked device type information.

**Comment by scamperfrozen** [comment]
did i miss this integration?

**Comment by RichieGP** [comment]
Hi, any updates here? Thank you
