### ISSUE TITLE
Colour control isn't working

### ISSUE THREAD

**Issue by arachnetech** [oznu/homebridge-gsh#8]
**Describe The Bug:**
When I change the colour of a coloured light it goes white.

**To Reproduce:**
Control a coloured light

**Expected behavior:**
Light changes to chosen colour and brightness

I've tested this with my own mqtt-based coloured lights (using homebridge-mqttthing), and with my Xiaomi gateway's light. 

P.S. It's great to see Google Home integration available within Homebridge finally. I've wanted to attempt this myself for a while, but never managed to find the time. Thank you!!

**Comment by arachnetech** [comment]
The issue appears to be that while the hue is being set correctly (as far as I can tell), the saturation is set to a very low value at the same time.

**Comment by oznu** [comment]
I'll check this out soon, thanks for reporting.

**Comment by oznu** [comment]
Hi @arachnetech,

This should be fixed in 1.0.3.

**Comment by arachnetech** [comment]
Thanks - colour is working beautifully now too!
