### ISSUE TITLE
GSH on HOOBS stopped working after 2.0.0 update

### ISSUE THREAD

**Issue by fizulnizam** [oznu/homebridge-gsh#81]
**Describe The Bug:**
The plugin stopped working after updating to 2.0.0 on HOOBS.

**To Reproduce:**
 Update to 2.0.0.

**Expected behavior:**
It works normally like how it should, loading on the logs page with the request to sync.

**Logs:**
 Bug reports that do not contain logs may be closed without warning.

```
16/10/2020, 17:57:50 The requested platform "google-smarthome" was not registered by any plugin.
16/10/2020, 17:57:50 Your config.json is requesting the platform "google-smarthome" which has not been published by any installed plugins.
```

**Homebridge Config:**

```json
{
            "platform": "google-smarthome",
            "plugin_map": {
                "plugin_name": "homebridge-gsh"
            },
            "name": "Google Smart Home plugin",
            "notice": "Keep your token a secret!",
            "token": "xxx",
            "debug": false,
            "twoFactorAuthPin": 0000
        },
```

**Screenshots:**

**Environment:**

* **Node.js Version**:  12.14.1
* **NPM Version**: 
* **Homebridge Version**: 3.26 
* **Homebridge GSH Plugin Version**: 2.0.0
* **Homebridge Config UI X Plugin Version**:
* **Operating System**: hoobs

**Comment by oznu** [comment]
This plugin requires Homebridge:

https://github.com/oznu/homebridge-gsh#configuration

See https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Migrate-From-HOOBS-To-Homebridge for details on how to move to a supported configuration. Hit me up on the Homebridge discord if you have any questions about this process.

**Comment by BobbySlope** [comment]
We are testing the next HOOBS update to support this new 2.0.0 plugin version. 
We will release an update for HOOBS soon. 
Contact us via info@hoobs.org and we can help you downgrade meanwhile.

**Comment by fizulnizam** [comment]
> We are testing the next HOOBS update to support this new 2.0.0 plugin version.
> We will release an update for HOOBS soon.
> Contact us via [info@hoobs.org](mailto:info@hoobs.org) and we can help you downgrade meanwhile.

How do I downgrade to GSH plugin 1.9.0?
