### ISSUE TITLE
How do i do if i don't want a two-factor check when i open my garage?

### ISSUE THREAD

**Issue by marcgrc** [oznu/homebridge-gsh#84]
Thank you 

**Describe Your Problem:**

**Logs:**

```
Show the Homebridge logs here.
Remove any sensative information.
```

**Homebridge Config:**

```json
Show your homebridge config.json here. 
Remove any sensitive information, such as your homebridge-gsh / google-smarthome token.
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Homebridge GSH Plugin Version**:
* **Homebridge Config UI X Plugin Version**:
* **Operating System**:

**Comment by oznu** [comment]
Hi @marcgrc,

The pin prompt is required to open a garage door (and other devices like unlocking locks, or disarming security systems). This cannot be disabled.
