### ISSUE TITLE
v2.0 Not working with Hoobs?

### ISSUE THREAD

**Issue by iamkylescode** [oznu/homebridge-gsh#86]
I updated to v2.0 in Hoobs. After doing so, all my hoobs devices stopped working in the Google Home app (running on iOS14). I unlinked my Homebridge account in Google Home and began to relink, but I was getting to a warning page that told me my instance of homebridge-gsh was not connected to the server. After trying many reconfigurations, I ended up downgrading to v1.9 and it all works again.

Did 2.0 take away support for Hoobs? Or is anyone else having a similar issue?

**Comment by oznu** [comment]
This plugin requires Homebridge v1.0.0 or later.

https://github.com/homebridge/homebridge-raspbian-image/wiki/How-to-migrate-from-HOOBS-to-Homebridge

**Comment by iamkylescode** [comment]
thanks for the reply @oznu. So just to be clear so that I understand: homebridge-gsh v1.9 works with both Hoobs ([](https://plugins.hoobs.org/plugin/homebridge-gsh)) and Homebridge v1.0 or later. But homebridge-gsh v2.0 no longer works with Hoobs, only Homebridge. Am I getting that right?

**Comment by oznu** [comment]
When HOOBS updates their software this plugin should continue working on the latest version. They are currently about 6 months behind Homebridge.
