### ISSUE TITLE
Create switch for integration and enabling/disabling of homekit automations

### ISSUE THREAD

**Issue by Krispy44** [oznu/homebridge-gsh#88]
**Is your feature request related to a problem? Please describe:**
Sometimes I want to directly turn on/off lights and smart plugs with my phone or google home, only to have automations setup with my motion sensors undo the direct command I just send to my smart home. For instance, I may want to have a nap in the living room, which has a motion sensor and smart plugs for lights, so I ask the google home to turn off the lights, subsequently roll over, which activates the motion sensor, thus turning on my lights.

**Describe the solution you'd like:**
If it is possible, this plugin (homebridge-gsh) could provide a "switch" to homekit that is set to on/off when google home turns a homebridge accessory on or off. This switch could then be integrated into homekit automations as a "condition". This switch integration in homekit automations would allow users to automatically disable homekit automations when google home is used to directly control homebridge accessories. 

Additionally, it would be very useful if this switch could have an integrated timer, so that the "switch" could turn off after a configured (in the homebridge-gsh settings in the homebridge web ui) set time and therefore re-enable the homekit automation it was blocking.

**Describe alternatives you've considered:**
The only solution I'm aware of right now is to set up recipes in IFTTT (google assistant trigger to webhook action) where a specific phrase would activate a virtual switch I could create in another homebridge plugin and perform a similar function. This poses a few problems:
1. That would require setting up a separate IFTTT recipe for every smart home scene I want to use google home for, which is impractical.
2. That would require giving up the ability for google assistant and google home to respond dynamically to voice requests because it requires specific phrase activations in IFTTT for each scene I want. This negates much of the usefulness of the homebridge-gsh plugin.

**Comment by oznu** [comment]
I think this plugin will allow you to archive what you want:

https://www.npmjs.com/package/homebridge-dummy

Any switch you create with that will appear in google home with this plugin.

**Comment by Krispy44** [comment]
That plugin unfortunately cannot do what I'm looking for. 

Essentially, I want any direct commands to google home to control accessories to override sensor-based automations in homekit. As far as I can tell, this is only possible if a google home command through a google speaker activates a dummy switch that is integrated in a homekit automation. The plugin you've mentioned above cannot do this because it cannot be activated by the interaction between google home and homebridge. 

Although I already use homebridge-gsh and it works well, I don't really know how it works. Is it possible for homebridge-gsh to tell when I say something like "hey google, turn on the living room lights"? I believe what I'm suggesting is only possible if homebridge-gsh is able to tell when I've controlled a homebridge accessory using a google speaker.
