### ISSUE TITLE
 Two-factor authentication

### ISSUE THREAD

**Issue by ankitseal** [oznu/homebridge-gsh#9]
Is it possible to implement Two-factor authentication for certain device types? Eg. For doorlocks:LockUnlock trait?
It would be really cool to be able to setup a pin for the lock
https://developers.google.com/actions/smarthome/develop/two-factor-authentication

**Comment by oznu** [comment]
Should be doable. One pin for all two factor challengers would be good enough?

**Comment by ankitseal** [comment]
Yeah! that would be great!
Ideal way for me would be to 
1)be able to select acknowledgment or pin method in config.json
2)select which accessories need 2FA in config.json

Thank you

**Comment by ankitseal** [comment]
Bump

**Comment by oznu** [comment]
Pin code challenges for unlocking a lock mechanise has been added as of v1.1.0.
