### ISSUE TITLE
temperature sensors  wil be not shown on google home as temp sensors.

### ISSUE THREAD

**Issue by Micha-123** [oznu/homebridge-gsh#91]
temp sensors wil be shown as a "sensor" in google home (see picture)

homebridge shows that sensors as temp sensor wel. but in google home i can only see "sensor" 
![Screenshot_20201211-080046](https://user-images.githubusercontent.com/35665484/101873507-56ee1780-3b87-11eb-97ca-09dabf20018e.png)

**Comment by oznu** [comment]
Temperature sensors do not support visual / touch controls in the Google Home app.

See this page for a full list of device types that support visual control:

https://developers.google.com/assistant/smarthome/develop/touch-controls

You should be able to ask google verbally for the status of the sensor.
