### ISSUE TITLE
Can't find supported devices

### ISSUE THREAD

**Issue by roelfoubert** [oznu/homebridge-gsh#93]
Hi,

I have a problem to link my homebridge with google smart home.
When I link my homebridge I get always the message: There went something wrong.
In homebridge it give: no supported device found for each accessory.
But they are all lamps and switches.

I'm using the latest version of node and npm

**Comment by roelfoubert** [comment]
I have multiple switches connected with LOGO-ts and a smart lamp with yeelight.
Google smart home doesn't find supported devices. 
Is there a way to fix this?

**Comment by oznu** [comment]
Do you have these accessories already exposed in Homebridge using the yeelight or other plugins?

**Comment by roelfoubert** [comment]
<img width="1907" alt="Schermafbeelding 2021-02-02 om 09 56 24" src="https://user-images.githubusercontent.com/9874656/106576029-ff43ab00-653c-11eb-964a-852f180b18de.png">
<img width="1911" alt="Schermafbeelding 2021-02-02 om 09 57 21" src="https://user-images.githubusercontent.com/9874656/106576078-0d91c700-653d-11eb-9bf8-fa97d3231ede.png">

Config:
{
    "bridge": {
        "name": "Home Server",
        "username": "CD:25:3D:E3:CE:44",
        "port": 51827,
        "pin": "010-45-154",
        "log": {
            "method": "file",
            "path": "/var/log/homebridge.log"
        }
    },
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "orange",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "yeelight",
            "name": "yeelight"
        },
        {
            "name": "Google Smart Home",
            "token": "*****",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome"
        }
    ],
    "accessories": [
        {
            "accessory": "Logo-TS",
            "name": "Inkom",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q1",
            "switchSetOn": "V1.1",
            "switchSetOff": "V1.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Hal 1e Verdiep",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q2",
            "switchSetOn": "V2.1",
            "switchSetOff": "V2.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Wc",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q3",
            "switchSetOn": "V3.1",
            "switchSetOff": "V3.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Garage",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q4",
            "switchSetOn": "V4.1",
            "switchSetOff": "V4.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Zetel",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q5",
            "switchSetOn": "V5.1",
            "switchSetOff": "V5.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Eettafel",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q8",
            "switchSetOn": "V8.1",
            "switchSetOff": "V8.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Slaapkamer",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q11",
            "switchSetOn": "V11.1",
            "switchSetOff": "V11.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Grote Kamer",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q12",
            "switchSetOn": "V12.1",
            "switchSetOff": "V12.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Kleine kamer",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q13",
            "switchSetOn": "V13.1",
            "switchSetOff": "V13.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Hal 2e Verdiep",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q14",
            "switchSetOn": "V14.1",
            "switchSetOff": "V14.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Badkamer",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q15",
            "switchSetOn": "V15.1",
            "switchSetOff": "V15.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Licht Keuken",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "Q17",
            "switchSetOn": "V17.1",
            "switchSetOff": "V17.2"
        },
        {
            "accessory": "Logo-TS",
            "name": "Alle Lichten",
            "interface": "modbus",
            "ip": "192.168.1.2",
            "port": 502,
            "type": "switch",
            "updateInterval": "1",
            "switchGet": "M20",
            "switchSetOn": "V20.1",
            "switchSetOff": "V20.2"
        },
        {
            "accessory": "FakeBulb",
            "name": "FakeBulb"
        }
    ]
}

I moved to a new house and when I relinked my account it can't find the devices.

**Comment by roelfoubert** [comment]
Has anyone found a solution?

**Comment by bykovo** [comment]
have the same issue. Has anybody found a solution please?

**Comment by StevenRCE0** [comment]
I'd like to bump the issue. I'm pretty sure that I have insecure mode enabled, accessories properly configured and account linked.

**Comment by rahooln** [comment]
following. having the same issue.

**Comment by valentinoeval** [comment]
Same problem
Closed issue but no solution provided ?
