### ISSUE TITLE
Fan compatibility

### ISSUE THREAD

**Issue by feededandrea** [oznu/homebridge-gsh#94]
**Describe The Bug:**
I can't turn my fan on, I can only turn it off. Also any posibilites of control speed in the future? Thank You

**Comment by meluvalli** [comment]
I’m also having an issue with fans. I don’t have a problem turning them on/off, but I can’t control the speed.  It’s only an on/off device yet my switch and homebridge both recognize it as dimmable.  This is an issue with this plugin.
