### ISSUE TITLE
Danalock not showing as "switch" in Google Home but works in Homekit?

### ISSUE THREAD

**Issue by casperse** [oznu/homebridge-gsh#95]
First what a great plugin! Kudos to your work! So easy to setup and get working!
I don't think this is a bug, more a configuration problem, So its a request for support - but I have been trying to solve it for a long time so thats why I am writing here :-)

**Describe Your Problem:**
I have the "Danalock" working on my Homekit as a switch so I know that the plugin from Smartthings is working and sending it as a switch into Homebridge to be used in Homekit, 
![image](https://user-images.githubusercontent.com/2026859/104447948-cdbe6c00-559c-11eb-8c43-e885410be10f.png)

- But when I add it to Google home through gsh it shows up as:
![image](https://user-images.githubusercontent.com/2026859/104447134-ad41e200-559b-11eb-9d64-226a9b16706a.png)
I did read the wiki and when I go to the "default" by terminal in Ubuntu I see the - I
![image](https://user-images.githubusercontent.com/2026859/104447229-ca76b080-559b-11eb-8bfc-c348f8c68c50.png)
Also enabled in the UI:
![image](https://user-images.githubusercontent.com/2026859/104447451-1c1f3b00-559c-11eb-8323-4a768bbafd80.png)
My configuration is pretty standard:

 

>       {
>             "name": "Google Smart Home",
>             "token": "secret token",
>             "notice": "Keep your token a secret!",
>             "twoFactorAuthPin": "1234",
>             "debug": false,
>             "accessoryFilter": [
>                 "HUB-AKTIVITET",
>                 "HUB-STUE",
>                 "Landroid Gurli",
>                 "james"
>             ],
>             "platform": "google-smarthome"
>         }`
> 

**Environment:**
![image](https://user-images.githubusercontent.com/2026859/104447717-77512d80-559c-11eb-840d-85efcc6f2fb0.png)

**Comment by oznu** [comment]
The google home app does not support visual control of locks.

You can ask Google verbally to unlock / lock the device.

**Comment by casperse** [comment]
Aaah THANKS!  (I remember now that Home assistant made virtual switches for these things, but without a PIN its to dangerous, somebody shouting from outside could open my front door LOL - I have set the two factor and it doesn't ask for the pin code?
But my Landroid lawnmover is asking for a Pin :-)

**Comment by oznu** [comment]
> I have set the two factor and it doesn't ask for the pin code?

it only requires it to unlock, not lock, I think.

**Comment by casperse** [comment]
One last Question, I have it all working now on the Google home mini, but google on my home doesn't work?
Is this by design? only local LAN access :-)

**Comment by oznu** [comment]
It should work on both the app and the smart speaker.

**Comment by casperse** [comment]
Thanks for helping me out! Much appreciated
