### ISSUE TITLE
Gear icon on locks and security alarm

### ISSUE THREAD

**Issue by DavidWhicker** [oznu/homebridge-gsh#96]
Hi

I was wondering if this is a limitation in google home app or not. 

I have linked my ring alarm to homebridge but when pulling through to the google home app it shows the icon but with a gear icon and I cannot control it. 

any ideas ?

**Comment by DavidWhicker** [comment]
![F40191F7-7FC0-406F-9B0A-7BB83DB903E0](https://user-images.githubusercontent.com/51021366/105642297-d6f2e700-5e80-11eb-8bcd-e637d2b965ca.png)

**Comment by oznu** [comment]
The google home app only allows visual control of a small number of devices; you have to use your voice for the others.
